"""Hyporheic function screening (functions plan Parts I-II).

Screening-tier functional estimates built on the flux-weighted residence-time distribution the
hydraulic run already produces. Everything here is hydraulic opportunity under stated assumptions,
never a calibrated measurement (framework §10.3). The Detailed tier, which runs a MODFLOW 6
transport or heat model, is a separate branch and does not live in this package.

Five sections: Nutrient Cycling, Pollutant Attenuation, Microplastic Retention, Habitat Creation
and Temperature Regulation. `registry` holds their parameters and citations, `pollutants` the cited
contaminant endpoints and the vocabulary each is allowed to use, and `screen` the calculations. All
three are Shiny-independent and operate on plain arrays so every number is unit-testable.

ATTENUATION, RETENTION, TRANSFORMATION -- never removal, outside denitrification. Nitrate is the
only endpoint in the app that is actually destroyed; everything else here is reversible sorption,
biotransformation or physical storage, and `pollutants.BANNED_WORDS` enforces that at import.
"""
from __future__ import annotations

from .helptext import (SOURCES, Help, Source, flat_text, format_sources, render_card,
                       source_labels)
from .pollutants import (
    BANNED_WORDS,
    CONCENTRATION_UNITS,
    DEFAULT_ENDPOINTS,
    ENDPOINT_METAL,
    ENDPOINT_ORGANIC,
    MASS_SCALES,
    PRESET_BY_KEY,
    PRESET_GROUPS,
    PRESETS,
    TERMS,
    Preset,
    get_preset,
    ordered_keys,
    validate_presets,
)
from .registry import (
    ANOXIC_THRESHOLD_HELP,
    ASSUMED_RATE_HELP,
    CITED_RATE_HELP,
    DO_ANOXIC_THRESHOLD_MG_L,
    DO_STREAM_DEFAULT_MG_L,
    DOWNWELLING_CELLS_HELP,
    HABITAT_POROSITY_HELP,
    HABITAT_VOLUME_HELP,
    HYDRAULICS_HELP,
    KIND_EXTENT,
    KIND_PARTICULATE,
    KIND_RESIDENCE_TIME,
    MICROPLASTIC_CAPTURE_HELP,
    MICROPLASTIC_GATE_HELP,
    MICROPLASTIC_RETENTION_HELP,
    MONOD_HALF_SATURATION_MG_N_L,
    NITRATE_DEFAULT_MG_N_L,
    NUTRIENT_AREAL_HELP,
    NUTRIENT_PER_KM_HELP,
    NUTRIENT_REDUCTION_HELP,
    OPPORTUNITY_CURVE_HELP,
    OXYGEN_CITATION,
    OXYGEN_CONSUMPTION_MG_L_DAY,
    OXYGEN_GATE_HELP,
    OXYGEN_HELP,
    OXYGEN_RATE_HELP,
    OXYGEN_TRANSFERABILITY,
    POLLUTANT_AREAL_HELP,
    POLLUTANT_PER_KM_HELP,
    POLLUTANT_REDUCTION_HELP,
    POLLUTANT_REGIME_HELP,
    PROCESSES,
    RETURNING_PATHS_HELP,
    RUN_SETTINGS_HELP,
    RATE_FIRST_ORDER_PER_DAY,
    RATE_TIMESCALE_H,
    RATE_ZERO_ORDER_MG_L_DAY,
    ROW_KINDS,
    SATURATION_CITATION,
    SECTION_ORDER,
    THERMAL_BANDS_HELP,
    THERMAL_BUFFERING_HELP,
    THERMAL_DIEL_HELP,
    THERMAL_FLOW_HELP,
    THERMAL_REGIME_HELP,
    FUNCTION_ORDER,
    FUNCTIONS,
    FunctionSpec,
    Mechanism,
    PaneCurve,
    PaneGroup,
    PaneKpi,
    PaneRow,
    ProcessSpec,
    function_for_process,
    function_keys,
    get_function,
    get_process,
    pane_node,
    process_keys,
    validate_functions,
    validate_registry,
    visible_rows,
)
from .screen import (
    ALPHA_MP_PER_KM,
    CAPTURE_CAP,
    DA_REACTION_LIMITED,
    DA_TRANSPORT_LIMITED,
    GATE_ATTACHMENT,
    GATE_EXCLUDED,
    GATE_NOTES,
    GATE_STRAINING,
    LAMBDA_F_PER_CM,
    NITRATE_BASIS,
    NITRATE_BASIS_LABEL,
    REGIME_NOTES,
    REGIME_REACTION,
    REGIME_RESPONSIVE,
    REGIME_TRANSPORT,
    SCREEN_METHOD_VERSION,
    SIZE_EXCLUSION_RATIO,
    STRAINING_ONSET_RATIO,
    UNSET,
    ScreeningInputs,
    first_order_saturation,
    opportunity_curve,
    removal_fractions,
    screen_extent,
    screen_particulate,
    screen_process,
    screen_reactive,
    screen_thermal,
    time_to_anoxia,
)

__all__ = [
    "FUNCTIONS", "FUNCTION_ORDER", "FunctionSpec", "Mechanism",
    "get_function", "function_keys", "function_for_process", "pane_node",
    "validate_functions",
    "PROCESSES", "SECTION_ORDER", "ProcessSpec", "get_process", "process_keys",
    "validate_registry", "KIND_RESIDENCE_TIME", "KIND_EXTENT", "KIND_PARTICULATE",
    "RATE_FIRST_ORDER_PER_DAY", "RATE_ZERO_ORDER_MG_L_DAY", "RATE_TIMESCALE_H",
    "DO_STREAM_DEFAULT_MG_L", "DO_ANOXIC_THRESHOLD_MG_L", "OXYGEN_CONSUMPTION_MG_L_DAY",
    "OXYGEN_CITATION", "OXYGEN_TRANSFERABILITY",
    "SCREEN_METHOD_VERSION", "ScreeningInputs", "screen_process", "screen_reactive",
    "screen_extent", "screen_thermal", "screen_particulate",
    "removal_fractions", "opportunity_curve",
    "time_to_anoxia", "NITRATE_BASIS", "NITRATE_BASIS_LABEL",
    # cited endpoints (screening reference §6) and the terminology they carry
    "PRESETS", "PRESET_BY_KEY", "PRESET_GROUPS", "DEFAULT_ENDPOINTS", "Preset", "get_preset",
    "ordered_keys", "validate_presets", "ENDPOINT_METAL", "ENDPOINT_ORGANIC", "TERMS",
    "BANNED_WORDS",
    "CONCENTRATION_UNITS", "MASS_SCALES",
    # exchange limitation (§4.4) and particulate coefficients (§5)
    "DA_REACTION_LIMITED", "DA_TRANSPORT_LIMITED", "REGIME_REACTION", "REGIME_RESPONSIVE",
    "REGIME_TRANSPORT", "REGIME_NOTES",
    "ALPHA_MP_PER_KM", "LAMBDA_F_PER_CM", "STRAINING_ONSET_RATIO", "SIZE_EXCLUSION_RATIO",
    "CAPTURE_CAP", "GATE_ATTACHMENT", "GATE_STRAINING", "GATE_EXCLUDED", "GATE_NOTES",
    "first_order_saturation", "MONOD_HALF_SATURATION_MG_N_L", "NITRATE_DEFAULT_MG_N_L",
    "SATURATION_CITATION", "UNSET",
    # structured help text (see helptext.py for why these are objects, not strings)
    "Help", "Source", "SOURCES", "format_sources", "source_labels", "render_card", "flat_text",
    "OXYGEN_GATE_HELP", "OXYGEN_HELP", "OXYGEN_RATE_HELP", "ANOXIC_THRESHOLD_HELP",
    "THERMAL_BANDS_HELP",
    # pane layout, so the registry names the metrics and app.py only formats them
    "PaneRow", "PaneGroup", "PaneKpi", "PaneCurve", "ROW_KINDS", "visible_rows",
    "ASSUMED_RATE_HELP", "CITED_RATE_HELP", "HYDRAULICS_HELP", "OPPORTUNITY_CURVE_HELP",
    "RUN_SETTINGS_HELP", "RETURNING_PATHS_HELP", "DOWNWELLING_CELLS_HELP",
    "NUTRIENT_REDUCTION_HELP", "NUTRIENT_AREAL_HELP", "NUTRIENT_PER_KM_HELP",
    "POLLUTANT_REDUCTION_HELP", "POLLUTANT_AREAL_HELP", "POLLUTANT_PER_KM_HELP",
    "POLLUTANT_REGIME_HELP", "MICROPLASTIC_RETENTION_HELP", "MICROPLASTIC_CAPTURE_HELP",
    "MICROPLASTIC_GATE_HELP",
    "HABITAT_VOLUME_HELP", "HABITAT_POROSITY_HELP", "THERMAL_BUFFERING_HELP",
    "THERMAL_FLOW_HELP", "THERMAL_DIEL_HELP", "THERMAL_REGIME_HELP",
]
